version: '3'

services:
  nlw-controller:
    container_name: nlw-controller
    hostname: docker-ubuntu-sandpit
    image: neotys/neoload-controller:9.2.1
    volumes:
      - /tmp/neoloadTest:/host
    environment:
      AGENT_XMX: -Xmx800m
    env_file:
      - ./nlweb-controller.env
      - ./nlweb.env
    links:
      - nlw-lg
    networks:
      - nlw
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 1024M
  nlw-lg:
    image: neotys/neoload-loadgenerator:9.2.1
    environment:
      AGENT_XMX: -Xmx800m
    env_file:
      - ./nlweb.env
    networks:
      - nlw
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 1024M
networks:
  nlw:
