version: '3'

services:
  nlw-controller:
    container_name: nlw-controller
    image: neotys/neoload-controller:9.2.1
    volumes:
      - /tmp/neoloadTest:/host
    environment:
      AGENT_XMX: -Xmx800m
      NEOLOADWEB_URL: ${NEOLOADWEB_URL}
      NEOLOADWEB_TOKEN: ${NEOLOADWEB_TOKEN}
      NEOLOADWEB_ZONE: ${NEOLOADWEB_ZONE}
    links:
      - nlw-lg
    networks:
      - nlw
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 1024M
  nlw-lg:
    image: neotys/neoload-loadgenerator:9.2.1
    environment:
      AGENT_XMX: -Xmx800m
      NEOLOADWEB_URL: ${NEOLOADWEB_URL}
      NEOLOADWEB_TOKEN: ${NEOLOADWEB_TOKEN}
      NEOLOADWEB_ZONE: ${NEOLOADWEB_ZONE}
    networks:
      - nlw
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 1024M
networks:
  nlw:
