name: NeoLoad test
on: workflow_dispatch
env:
  TEST_NAME: '"NeoloadPOC"'
  WORKSPACE_NAME: '"Evolution"'
  VERSION: '9.2.1'
  NEOLOADWEB_TOKEN: ${{ secrets.NEOLOADWEB_TOKEN }}
  ZONE: ${{ secrets.ZONE }}
  CREDENTIAL: ${{ secrets.CREDENTIAL }}

jobs:
  nightly_build_demo_app:
    name: Neoload POC
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - api_url: https://neoload-api.saas.neotys.com/
    steps:
    
      - name: Checkout
        uses: actions/checkout@v3
        
      - name: Credential
        run: |
          echo "Hello" | base64 > ./nlweb.env
          cat ./nlweb.env
    
      - name: "Start Controller and LGs"
        run: docker-compose -f nlweb-infra-scale.yml up --scale nlw-lg=2 --remove-orphans
      
      - name: "Wait for infrastructure"
        run: sleep 60
        
      - name: "Install NeoLoad CLI"
        run: pip3 install -U neoload
        
      - name: "NeoLoad Login"
        run: neoload login --url ${{ matrix.api_url }} --workspace ${{ env.WORKSPACE_NAME }} ${{ env.NEOLOADWEB_TOKEN }}
        
      - name: "NeoLoad run test"
        run: >
          neoload run 
          --external-url $GITHUB_SERVER_URL/$GITHUB_REPOSITORY/actions/runs/$GITHUB_RUN_ID 
          --external-url-label "Github Action Run ${{ env.VERSION }}.$GITHUB_RUN_NUMBER" 
          --name "Demo app regression test - Github build ${{ env.VERSION }}.$GITHUB_RUN_NUMBER" 
          --description "Neoload POC" 
          ${{ env.TEST_NAME }}
          
      - name: Stop containers
        if: always()
        run: docker-compose -f nlweb-infra-scale.yml down
        
      - name: "Generate Test Report"
        run: neoload test-results junitsla

      - name: "Publish Test Report"
        if: ${{ always() }}
        uses: scacap/action-surefire-report@v1
        with:
          report_paths: junit-sla.xml
          fail_on_test_failures: true
