name: NeoLoad test
on: workflow_dispatch
env:
  TEST_NAME: '"NeoloadPOC"'
  WORKSPACE_NAME: '"Evolution"'
  VERSION: '9.2.1'
  CREDENTIAL: ${{ secrets.CREDENTIAL }}

jobs:
  neoload_poc:
    permissions: write-all
    name: Neoload POC
    runs-on: ubuntu-latest
    env:
          NEOLOADWEB_URL: 'https://neoload-api.saas.neotys.com/'
          NEOLOADWEB_TOKEN: ${{ secrets.NEOLOADWEB_TOKEN }}
          NEOLOADWEB_ZONE: ${{ secrets.NEOLOADWEB_ZONE }}
    steps:
    
      - name: Checkout
        uses: actions/checkout@v3
        
      - name: Prepare Credentials
        run: |
          echo ${{ secrets.CREDENTIAL }} | base64 -d > ./nlweb.env
    
      - name: "Start Controller and LGs"        
        run: docker-compose -f nlweb-infra-scale.yml up --scale nlw-lg=2 --remove-orphans -d -e NEOLOADWEB_URL=${{ env.NEOLOADWEB_TOKEN }} -e NEOLOADWEB_TOKEN=${{ env.NEOLOADWEB_TOKEN }} -e NEOLOADWEB_ZONE=${{ env.NEOLOADWEB_ZONE }}
        
      - name: "Wait for infrastructure"
        run: sleep 30
        
      - name: "Install NeoLoad CLI"
        run: pip3 install -U neoload
        
      - name: "NeoLoad Login"
        run: neoload login --url ${{ env.NEOLOADWEB_URL}} --workspace ${{ env.WORKSPACE_NAME }} ${{ env.NEOLOADWEB_TOKEN }}
        
      - name: "NeoLoad run test"
        run: >
          neoload run 
          --external-url $GITHUB_SERVER_URL/$GITHUB_REPOSITORY/actions/runs/$GITHUB_RUN_ID 
          --external-url-label "Github Action Run ${{ env.VERSION }}.$GITHUB_RUN_NUMBER" 
          --name "Demo app regression test - Github build ${{ env.VERSION }}.$GITHUB_RUN_NUMBER" 
          --description "Neoload POC" 
          ${{ env.TEST_NAME }}
        
      - name: "Generate Test Report"
        run: neoload test-results --junit-file  ${{ github.workspace }}/junit-sla.xml junitsla

      - name: "Publish Test Report"
        if: always()
        uses: scacap/action-surefire-report@v1
        with:
          report_paths:  ${{ github.workspace }}/junit-sla.xml
          fail_on_test_failures: true
          
      - name: Stop containers
        if: always()
        run: docker-compose -f nlweb-infra-scale.yml down
