name: Test Multi git
on: workflow_dispatch
jobs:
  neoload_poc:
    permissions: write-all
    name: test
    runs-on: ubuntu-latest
    steps:
    
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: 'true'
          token: ${{ secrets.ACCESS_TOKEN_GITHUB }}
          
        
      - name: Check out my other private repo
        uses: actions/checkout@v3
        with:
          repository: boitcex/testNeoloadGit
          path: ./ElegantNetworkingRoot
          token: ${{ secrets.ACCESS_TOKEN_GITHUB }}
          
      - name: Show Working directory
        run: ls
        
  
