name: Test Multi git
on: workflow_dispatch
jobs:
  neoload_poc:
    name: test
    runs-on: ubuntu-latest
    steps:
    
      - name: CHECKOUT MAIN REPO where workflow located
        uses: actions/checkout@v3
        with:
          path: ./flow

      - name: CHECKOUT REPO 2 in the same workflow
        uses: actions/checkout@v3
        with:
          repository: boitcex/testNeoloadGit
          path: ./scripts
          token: ${{ secrets.ACCESS_TOKEN_GITHUB }}
          
      - name: Show Working directory REPO FLOW
        run: ls -lah ${{ github.workspace }}/flow
        
      - name: Show Working directory REPO SCRIPTS
        run: ls -lah ${{ github.workspace }}/scripts
    
