name: Test Multi git
on: workflow_dispatch
jobs:
  neoload_poc:
    name: test
    runs-on: ubuntu-latest
    steps:
    
      - name: CHECKOUT MAIN REPO where workflow located
        uses: actions/checkout@v3

      - name: CHECKOUT REPO 2 in the same workflow
        uses: actions/checkout@v3
        with:
          repository: boitcex/testNeoloadGit
          path: ./ElegantNetworkingRoot
          token: ${{ secrets.ACCESS_TOKEN_GITHUB }}
    
